### ISSUE TITLE
The issue is there is no issue.

### ISSUE THREAD

**Issue by InvertedReality** [githubstudent/gh-for-developers-july#2]
Hi!

**Comment by psprings** [comment]
Issue-ception
http://www.google.com/imgres?imgurl=https://www.drupal.org/files/images/0715-INCEPTION-movie-review_full_600.jpg&imgrefurl=https://www.drupal.org/project/inception&h=400&w=600&tbnid=EKkcYjgYz4T6VM:&zoom=1&docid=qqaK3Hz11MOJTM&ei=djmdVYG9CsGcsQXj64HwBQ&tbm=isch&ved=0CFYQMygaMBo

**Comment by githubstudent** [comment]
Comment is comment.
